trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
  displayName: 'Use Python 3.11'

- script: |
    cd backend
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Backend Dependencies'

- task: ArchiveFiles@2
  displayName: 'Archive Backend'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/backend'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Backend Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend.zip'
    ArtifactName: 'backend-build'
    publishLocation: 'Container'

- task: AzureWebApp@1
  displayName: 'Deploy Backend to App Service'
  inputs:
    azureSubscription: 'cost-estimator-sc'
    appType: 'webAppLinux'
    appName: 'costestimatorbackend'
    package: '$(Build.ArtifactStagingDirectory)/backend.zip'
    runtimeStack: 'PYTHON|3.11'
    startUpCommand: 'cd /home/site/wwwroot && uvicorn app.main:app --host 0.0.0.0 --port 8000'
  env:
    AZURE_HTTP_USER_AGENT: ''